name: Testcases

on:
  pull_request:
    branches: [master]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --file=.gitmodules submodule.test_submodule.url https://hariharan-dev:${{ secrets.CI_PAT }}@github.com/hariharan-dev/test_submodule.git
          git submodule sync
          git submodule update --init --recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
